### ISSUE TITLE
Normal text after Emoji/Unicode breaks .Split()

### ISSUE THREAD

**Issue by alexthekid07** [janpieterz/Sms.Splitter#2]
Trying to split a string with emoji seems to break Sms.Splitter.Splitter.Split() resulting in:
`Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Sms.Splitter.UnicodeSplitter.AddPart(SplitResult result, MessageWalker& walker, String content, Nullable 1 partEnd)
   at Sms.Splitter.UnicodeSplitter.Split(String content)
   at Sms.Splitter.Splitter.Split(String content, CharacterSet overrideCharacterSet)`

Here is what I was trying to split:
`This is a long message that I'd like to see be sent to me, split into proper parts and whatnot. 😊 😎 😇 😈 😋 😏 😌 😁 😀 😂 test test test`

Stangely, it seems if you remove the trailing "test test test" it doesn't error.

**Comment by alexthekid07** [comment]
Its interesting that the message I posted above does not work, but this test you did works fine:
`Snowman shows off! ☃ Snowman shows off! ☃ Snowman shows off! ☃ Snowman shows off!`

**Comment by janpieterz** [comment]
Interesting, must be some encoding oddity.

**Comment by janpieterz** [comment]
Would you be able to add some unit tests for these, a valid one with a normal flow like the Snowman, a valid one without `test test test` and an invalid one with `test test test`?

**Comment by Zeek2** [comment]
I think I have a test case for this and a fix :)
Thanks for sharing this useful lib. Found a bug for various long, complex Unicode strings, for example this one:
"මට නැහැaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccc sdddddddddddddddddddddddddddddddddddddddddddddddddddd"

I have added this to my copy of your final splitter test thus:
[InlineData("මට නැහැaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccc sdddddddddddddddddddddddddddddddddddddddddddddddddddd", 37)]

**Comment by Zeek2** [comment]
The fix I have is in UnicodeSplitter.cs at line 79, in AddPart().

        result.Parts.Add(new SplitPart()
        {
            Bytes = walker.Bytes,
            Length = walker.Length,
            // Was: Content = partEnd.HasValue ? content.Substring(walker.PartStart, partEnd.Value + 1) : content.Substring(walker.PartStart)
            Content = partEnd.HasValue ? content.Substring(walker.PartStart, (partEnd.Value + 1) - walker.PartStart) : content.Substring(walker.PartStart)   // <-- Fix
        });

I think the problem was that substring was incorrectly called with startIndex and endIndex but needs instead to be called with startIndex and length. I haven't exhaustively tested it yet but the fix above works for the test case shown above plus another involving a long emoji, so it is looking promising ;)

**Comment by alexthekid07** [comment]
@Zeek2 I am currently implementing something similar as a result of [this issue](url) on another SMS-splitting library if you're interested

**Comment by Zeek2** [comment]
Hi Alex. Do you prefer SMSHelpers over Sms.Split?

**Comment by janpieterz** [comment]
@Zeek2 Happy to take a pull request with the fix and a unit test added for this.

**Comment by Zeek2** [comment]
Hi Jan, I have created 2 pull requests, one for the fix and one for 2 new test messages.  I am new to this but I am thinking the next step is for you to review and accept or reject.  If you need anything else from me, just let me know ;)

**Comment by Zeek2** [comment]
Hold off Jan. We have an off-by-one on SMS message length now, which may or may not be related. Will try to get back by tomorrow.

**Comment by janpieterz** [comment]
@Zeek2 No worries, just ping me when you're ready.
I see you have two branches on your fork, you'll have to click a button that says _New pull request_ on your fork, and you should be able to direct it to my repository. Check out https://help.github.com/en/articles/creating-a-pull-request-from-a-fork for more info.

**Comment by Zeek2** [comment]
Thanks Jan.  The length issue affects both GSM and Unicode (when special chars. included), so unrelated to the fix. The TotalLength provided by SmsSplitter is not what we expect/want - we want the # of characters of whatever character type (GSM/UCS-2) is used; however I am able to simply calculate what we need thus:

			// # Total # of 7-bit GSM7 or 2-byte UCS-2 characters, as appropriate.
			int TotalNumberOfChars = (result.CharacterSet == CharacterSet.Unicode) ?  result.TotalBytes / 2 : result.TotalBytes;

Not sure if the unexpected TotalLength is wrong (a bug) or simply something different from what we want/expect.  I think TotalLength probably counts each character or symbol or emoji as 1 instance - even for extended symbols (like this one which requires 7 unicode characters to express: 👁️‍🗨️ or this one which take 4 unicode characters: 👁️‍. ref. https://unicode.org/emoji/charts/full-emoji-list.html ).

I will create a pull request for the Unhandled Exception fix.

**Comment by janpieterz** [comment]
Fixed by #8
