### ISSUE TITLE
Update Sms.Splitter to use .NET 4.7.1 & xUnit 2.4.1?

### ISSUE THREAD

**Issue by Zeek2** [janpieterz/Sms.Splitter#5]
FYI I updated my version of Sms.Splitter to use the latest version of .NET (currently 4.7.2) - which necessitated reinstalling nuget packages (I just reinstalled everything at the original version).

At VS2017's prompting, I also upgraded the xUnit Nuget packages (from 2.2 to 2.4.1).

Would it be appropriate to include such changes in a pull request to Jan's master?

**Comment by janpieterz** [comment]
@Zeek2 I'd be more interested in moving this to a NetStandard library, with the new project model.
What's the reason for moving to .NET 4.7.1 compared to 4.5 for you?

**Comment by Zeek2** [comment]
Hi Jan, yes probably better to leave it for now, then others can upgrade it to whatever level is appropriate for them, if necessary.  We use .NET 4.7.2, or whatever the latest released version is. Just wanted to ensure others realize Sms.Splitter still works & remains current.  A NetStandard library sounds like an excellent idea :).

**Comment by janpieterz** [comment]
Great, I'll convert it to NetStandard before pushing the next version to Nuget.

**Comment by janpieterz** [comment]
I'll close this and merge the pull request once we merge #4
