### ISSUE TITLE
TotalLength result field is sometimes lower than expected when emoji, extended char or complex font included

### ISSUE THREAD

**Issue by Zeek2** [janpieterz/Sms.Splitter#6]
This TotalLength issue affects both GSM and Unicode SMS messages when extended chars. are included. The TotalLength provided by SmsSplitter is not what we expect, we need the count of the # of characters of whatever character type (GSM/UCS-2) is used.  I think this is probably a bug.  TotalLength undercounts the # of characters required to represent extended character and/or emojis. 

However there is a **workaround**, I am able tocalculate the total length that we need from the result provided by Sms.Splitter thus:

			// # Total # of 7-bit GSM7 or 2-byte UCS-2 characters, as appropriate.
			int TotalNumberOfChars = (result.CharacterSet == CharacterSet.Unicode) ?  result.TotalBytes / 2 : result.TotalBytes;

**Comment by Zeek2** [comment]
We found the following webtool useful. As well as counting character and bytes,  it displays the entire SMS packet structure underneath:
https://messente.com/documentation/tools/sms-length-calculator

**Comment by Zeek2** [comment]
FYI **result.RemainingInPart is correct**.  It works well with the TotalNumberOfChars calculation that we use (shown in above code sample), with both GSM-7, with and without extended characters, and UCS-2, with or without extended chars/emojis.

**Comment by janpieterz** [comment]
@Zeek2 Love that you're diving deep into this, happy to jump onboard and correct this.

I'd be happy taking a pull request for this part, either with a unit test failing so I can build on the core, or with a fix if you find it.

**Comment by Zeek2** [comment]
OK, I will try to produce some xUnit tests in the near future. 

Not sure if I will get to debug this, the workaround fixed it for us.  FYI I tried incrementing the length count in both (GSM-7 & Unicode) splitters, where they handle extended characters (in the surrogate check clause) but that seemed to upset other counts & broke several unit tests - but I expect that's where a fix would need to go.  I was hoping that just raising the issue might trigger some realization/memory for you, about how the counts interact perhaps, although I suppose its been a few years since you've had your head in it, and I guess this was a port of the JavaScript version by CodeSleuth, so not necessarily completely familiar to you.  BTW the JavaScript version does not have this bug, at least judging from the sample/test webpage.

Test-wise, it would be good to cover TotalLength checks for:
1. Short GSM-7 string, with and without one and more extended chars.
2. Long GSM-7 , with and without one and  more extended chars.
3. Short UCS-2 string, with and without one and more extended chars/emojis.
4. Long UCS-2 , with and without one and  more extended chars/emojis.
eventually.

**Comment by Zeek2** [comment]
New pull request submitted with a new test case & several test-strings for TotalLength - most of these will fail because of the issue raised.  Also added a couple more test-strings to the existing TotalRemaing test, these pass.

**Comment by Zeek2** [comment]
Jan, I have been thinking this issue over.  Perhaps the workaround - which I currently have implemented in my own calling code - is also the fix for Sms.Splitter?  The TotalLength currently output is clearly used and required by the existing Sms.Splitter functionality but perhaps it should be considered for internal use only?  The workaround value calculated (see earlier post above) could perhaps be output instead, or as well as it.

**Comment by janpieterz** [comment]
Agree there should be a fix into Sms.Splitter for this.
We'll probably need a new value for this and the other one. 

I'm envisioning the following two options:

- The amount of characters (visible items), is 1 for 😍, 1 for 👁️‍🗨️
- The amount of characters needed within the character set, is 2 for 😍 and 5 for 👁️‍🗨️

Shouldn't be too difficult, just need to sit down and spend some time ensuring we do it right for all variations.

**Comment by Zeek2** [comment]
I just had a quick look at the code concerned. 3 approaches occurred to me.:

1. My workaround could be applied just once at the end of the process, as shown above. 

2. Alternatively  it could be added more in 2 places, in the 2 splitters, which would eliminated the need for the if-check (implemented as a tenary operator in the workaround).

a.For example, we could set for each message part:

e.g In UnicodeSplitter.cs
          result.TotalBytes += walker.Bytes;
          result.TotalLength += walker.Length;
          result.TotalCharacters += walker.Bytes/2; // <-- New-line

e.g. In GSM Splitter
            result.TotalBytes += walker.Bytes;
            result.TotalLength += walker.Length;
            result.TotalCharacters += walker.Bytes;

b. Alternatively, we could just calculate it once, in each Splitter, at the end of processing, as is already done for the TotalRemaining by the call to CalculateRemainingInPart(). 

However, there is value in having the count for each message-part - for example the test URL above displays the characters in each message-part, in its "Detailed View" visualization underneath the text input box.  So something like option 2a would be my suggestion.

**Comment by janpieterz** [comment]
Nice, cheers.
I like it both in each part as well as total. 
There's value in both, and exactly the type of complexity the library is meant to solve.

**Comment by Zeek2** [comment]
Ok.  I have made the enhancement and run it against the proposed new xUnit tests and they all pass.  I will try to upload the changes in the next day or so.

**Comment by Zeek2** [comment]
Hi Jan, is there a problem including the enhancement?  I think I missed a Git branching step somewhere but I did manage to merge the differences without problem. FYI I have some additional tests in a separate test app. which all passed OK.

**Comment by janpieterz** [comment]
Hi @Zeek2 
Nothing wrong with your code, I haven't had time to dive a little deeper. Where I got stuck instead of just accepting it is the difference between TotalLength and TotalCharacters. I'll just need to wrap my head around it, but when changing unit tests for `TestFullGsmSplitter` and `TestFullUnicodeSplitter` to measure total characters there was a discrepancy I couldn't fully rationalize.

**Comment by Zeek2** [comment]
I don't think you need to change the existing unit tests.  I have added new tests for the new TotalCharacters field. TotalLength is retained for backwards compatibility and internal use, so the existing unit tests should, I would think, likewise be retained for backwards compatibility.

Re. discrepancy, are you familiar with:

1. The message-part shortening that occurs when a message requires more than one message-part (e.g. GSM-7 160->153 and UCS-2 70->67)? 

2. The 10 GSM extended characters that use 2-chars?

**Comment by janpieterz** [comment]
Apologies, taken me longer than I intended to get back to this.
I'm familiar with both the extended characters as well as the message-part shortening. 

Where I feel I need to dig deeper are these examples (taken from the TestTotalLengthParts tests):

![image](https://user-images.githubusercontent.com/383634/56409227-6749d400-6278-11e9-90bc-a115baaf3ca4.png)
Here I would expect the parts[0] to have the same amount of Characters as the total.

-----------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/383634/56409255-7fb9ee80-6278-11e9-9196-a5e8442bca1e.png)
Here the bytes are, I think correctly, 14, the characters correctly 7 but the length is 5? The discrepancy between the 7 and 5 I can't wrap my head around.  The Characters of the part[0] is also missing, this might simply be a missing implementation detail there. This makes me think the length calculation is simply wrong and should probably be removed, it works great for single utf8 chars, but not for combined ones.

-----------------------------------------------------------------------------------------

**Comment by Zeek2** [comment]
Are either of the original length fields, Parts[x].Length and TotalLength, used internally by the Sms.Splitter assembly?  I am not looking at the code currently but I had the impression that they were, or might be, used internally.

**Comment by janpieterz** [comment]
Nope, they were just external. I think, copied over from the original, it used a wrong terminology/counting combination.
Fixed with #10 and pushed to nuget as version 2.0.0
